dist: xenial
language: c
compiler: gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y fakeroot
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y autoconf
  - sudo apt-get install -y automake
  - sudo apt-get install -y zlib1g-dev
  - sudo apt-get install -y libbz2-dev
  - sudo apt-get install -y sharutils
script: ACLOCAL=aclocal-1.15 AUTOMAKE=automake-1.15 ./configure --with-zlib --with-bzlib --prefix=/usr && make all && make distcheck && make dist-bzip2 && make dist-xz && make dist-zip && fakeroot make DESTDIR=${HOME}/sysroot install
